---
# In-Place Pod Vertical Scaling (CPU Resize) Demonstration
# This demo shows how to resize pod CPU/memory without restarting the container
# Kubernetes Version: 1.27+ (requires InPlacePodVerticalScaling feature gate)
# Feature: Allows changing CPU/memory limits on running pods
#
# IMPORTANT: This feature requires the InPlacePodVerticalScaling feature gate
# to be enabled on both kube-apiserver and kubelet.
#
# AKS Compatibility Notes:
# - As of early 2024, InPlacePodVerticalScaling is NOT enabled by default in AKS
# - This is a beta feature in Kubernetes 1.27+ that AKS may not have enabled
# - Check AKS release notes for feature gate availability in your version
# - Alternative for AKS: Use Vertical Pod Autoscaler (VPA) with recreate mode
#   or update deployment specs to trigger rolling updates
# - For production workloads, consider using VPA or HPA instead
# - To verify if the feature is available:
#   kubectl get --raw /api/v1/pods | grep -i resize
#
# Testing Instructions:
# 1. Apply the manifest: kubectl apply -f pod-cpu-resize-demo.yaml
# 2. Check pod status: kubectl get pod reactor-cpu-resize-demo
# 3. Watch the cpu-monitor logs: kubectl logs -f reactor-cpu-resize-demo -c cpu-monitor
# 4. Resize CPU (if feature is enabled):
#    kubectl patch pod reactor-cpu-resize-demo --patch '{"spec":{"containers":[{"name":"reactor","resources":{"limits":{"cpu":"200m"},"requests":{"cpu":"200m"}}}]}}'
# 5. Observe the cpu-monitor container showing updated CPU quota
#
apiVersion: v1
kind: Pod
metadata:
  name: reactor-cpu-resize-demo
  labels:
    app: reactor
    demo: cpu-resize
spec:
  containers:
  - name: reactor
    image: nginx:latest
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"
    resizePolicy:
    - resourceName: cpu
      restartPolicy: NotRequired
    - resourceName: memory
      restartPolicy: NotRequired

  - name: cpu-monitor
    image: busybox:latest
    command:
    - /bin/sh
    - -c
    - |
      echo "Starting CPU quota monitor..."
      while true; do
        if [ -f /sys/fs/cgroup/cpu.max ]; then
          echo "[$(date '+%Y-%m-%d %H:%M:%S')] CPU quota: $(cat /sys/fs/cgroup/cpu.max)"
        else
          echo "[$(date '+%Y-%m-%d %H:%M:%S')] cpu.max not found (checking legacy path)"
          if [ -f /sys/fs/cgroup/cpu/cpu.cfs_quota_us ]; then
            QUOTA=$(cat /sys/fs/cgroup/cpu/cpu.cfs_quota_us)
            PERIOD=$(cat /sys/fs/cgroup/cpu/cpu.cfs_period_us)
            echo "[$(date '+%Y-%m-%d %H:%M:%S')] CPU quota: $QUOTA/$PERIOD"
          fi
        fi
        sleep 2
      done
    resources:
      requests:
        cpu: "10m"
        memory: "32Mi"
      limits:
        cpu: "50m"
        memory: "64Mi"
    resizePolicy:
    - resourceName: cpu
      restartPolicy: NotRequired
    - resourceName: memory
      restartPolicy: NotRequired

  restartPolicy: Always
